[bumpver]
current_version = "5.0.7"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"README.md" = [
    "{version}",
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"include/OptFCore/FCore.hpp" = [
    "{version}"
]
"docs/source/conf.py" = [
    "{version}",
]
